export const towns = new Map([
    ["Choapan", [
        { code: 189, name: "San Juan Comaltepec" },
        { code: 205, name: "San Juan Lalana" },
        { code: 212, name: "San Juan Petlapa" },
        { code: 460, name: "Santiago Choápam" },
        { code: 468, name: "Santiago Jocotepec" },
        { code: 498, name: "Santiago Yaveo" }
    ]],
    ["Coixtlahuaca", [
        { code: 18, name: "Concepción Buenavista" },
        { code: 47, name: "San Cristóbal Suchixtlahuaca" },
        { code: 129, name: "San Francisco Teopan" },
        { code: 151, name: "San Francisco Tlapancingo" },
        { code: 176, name: "San Juan Bautista Coixtlahuaca" },
        { code: 256, name: "San Mateo Tlapiltepec" },
        { code: 283, name: "San Miguel Tequixtepec" },
        { code: 287, name: "San Miguel Tulancingo" },
        { code: 424, name: "Santa Magdalena Jicotlán" },
        { code: 462, name: "Santa María Nativitas Plumas" },
        { code: 484, name: "Santiago Ihuitlán Plumas" },
        { code: 488, name: "Santiago Tepetlapa" },
        { code: 548, name: "Santo Domingo Tonalá" },
        { code: 552, name: "Santo Tomás Ocotepec" }
    ]],
    ["Cuicatlán", [
        { code: 19, name: "Concepción Pápalo" },
        { code: 24, name: "Cuyamecalco Villa de Zaragoza" },
        { code: 27, name: "Chiquihuitlán de Benito Juárez" },
        { code: 98, name: "San Andrés Teotilálpam" },
        { code: 139, name: "San Francisco Chapulapa" },
        { code: 177, name: "San Juan Bautista Cuicatlán" },
        { code: 182, name: "San Juan Bautista Tlacoatzintepec" },
        { code: 220, name: "San Juan Tepeuxila" },
        { code: 276, name: "San Miguel Santa Flor" },
        { code: 311, name: "San Pedro Jaltepetongo" },
        { code: 313, name: "San Pedro Jocotipac" },
        { code: 326, name: "San Pedro Sochiapam" },
        { code: 330, name: "San Pedro Teutila" },
        { code: 355, name: "Santa Ana Cuauhtémoc" },
        { code: 425, name: "Santa María Pápalo" },
        { code: 436, name: "Santa María Texcatitlán" },
        { code: 438, name: "Santa María Tlalixtac" },
        { code: 478, name: "Santiago Nacaltepec" },
        { code: 527, name: "Santos Reyes Pápalo" },
        { code: 558, name: "Valerio Trujano" }
    ]],
    ["Centro", [
        { code: 23, name: "Cuilápam de Guerrero" },
        { code: 67, name: "Oaxaca de Juárez" },
        { code: 83, name: "San Agustín de las Juntas" },
        { code: 87, name: "San Agustín Yatareni" },
        { code: 91, name: "San Andrés Huayapam" },
        { code: 92, name: "San Andrés Ixtlahuaca" },
        { code: 107, name: "San Antonio de la Cal" },
        { code: 115, name: "San Bartolo Coyotepec" },
        { code: 157, name: "San Jacinto Amilpas" },
        { code: 174, name: "Ánimas Trujano" },
        { code: 310, name: "San Pedro Ixtlahuaca" },
        { code: 342, name: "San Raymundo Jalpan" },
        { code: 350, name: "San Sebastián Tutla" },
        { code: 375, name: "Santa Cruz Amilpas" },
        { code: 385, name: "Santa Cruz Xoxocotlán" },
        { code: 390, name: "Santa Lucía del Camino" },
        { code: 399, name: "Santa María Atzompa" },
        { code: 403, name: "Santa María Coyotepec" },
        { code: 409, name: "Santa María del Tule" },
        { code: 519, name: "Santo Domingo Tomaltepec" },
        { code: 553, name: "Tlalixtac de Cabrera" }
    ]],
    ["Ejutla", [
        { code: 15, name: "Coatecas Altas" },
        { code: 17, name: "La Compañía" },
        { code: 28, name: "Heroica Ciudad de Ejutla de Crespo" },
        { code: 69, name: "La Pe" },
        { code: 80, name: "San Agustín Amatengo" },
        { code: 101, name: "San Andrés Zabache" },
        { code: 203, name: "San Juan Lachigalla" },
        { code: 238, name: "San Martín de los Cansecos" },
        { code: 241, name: "San Martín Lachilá" },
        { code: 268, name: "San Miguel Ejutla" },
        { code: 534, name: "San Vicente Coatlán" },
        { code: 542, name: "Taniche" },
        { code: 563, name: "Yogana" }
    ]],
    ["Etla", [
        { code: 33, name: "Guadalupe Etla" },
        { code: 45, name: "Magdalena Apasco" },
        { code: 63, name: "Nazareno Etla" },
        { code: 77, name: "Reyes Etla" },
        { code: 84, name: "San Agustín Etla" },
        { code: 102, name: "San Andrés Zautla" },
        { code: 135, name: "San Felipe Tejalapan" },
        { code: 150, name: "San Francisco Telixtlahuaca" },
        { code: 161, name: "San Jerónimo Sosola" },
        { code: 175, name: "San Juan Bautista Atatlahuca" },
        { code: 178, name: "San Juan Bautista Guelache" },
        { code: 179, name: "San Juan Bautista Jayacatlán" },
        { code: 193, name: "San Juan del Estado" },
        { code: 227, name: "San Lorenzo Cacaotepec" },
        { code: 293, name: "San Pablo Etla" },
        { code: 294, name: "San Pablo Huitzo" },
        { code: 338, name: "Villa de Etla" },
        { code: 426, name: "Santa María Peñoles" },
        { code: 483, name: "Santiago Suchilquitongo" },
        { code: 487, name: "Santiago Tenango" },
        { code: 494, name: "Santiago Tlazoyaltepec" },
        { code: 531, name: "Santo Tomás Mazaltepec" },
        { code: 539, name: "Soledad Etla" }
    ]],
    ["Huajuapan", [
        { code: 4, name: "Asunción Cuyotepeji" },
        { code: 22, name: "Cosoltepec" },
        { code: 32, name: "Fresnillo de Trujano" },
        { code: 39, name: "Heroica Ciudad de Huajuapan de León" },
        { code: 55, name: "Mariscala de Juárez" },
        { code: 89, name: "San Andrés Dinicuiti" },
        { code: 160, name: "San Jerónimo Silacayoapilla" },
        { code: 164, name: "San Jorge Nuchita" },
        { code: 165, name: "San José Ayuquila" },
        { code: 181, name: "San Juan Bautista Suchitepec" },
        { code: 237, name: "San Marcos Arteaga" },
        { code: 245, name: "San Martín Zacatepec" },
        { code: 261, name: "San Miguel Amatitlán" },
        { code: 340, name: "San Pedro y San Pablo Tequixtepec" },
        { code: 352, name: "San Simón Zahuatlán" },
        { code: 373, name: "Santa Catarina Zapoquila" },
        { code: 381, name: "Santa Cruz Tacache de Mina" },
        { code: 400, name: "Santa María Camotlán" },
        { code: 455, name: "Santiago Ayuquililla" },
        { code: 456, name: "Santiago Cacaloxtepec" },
        { code: 459, name: "Santiago Chazumba" },
        { code: 462, name: "Santiago Huajolotitlán" },
        { code: 476, name: "Santiago Miltepec" },
        { code: 520, name: "Santo Domingo Tonalá" },
        { code: 524, name: "Santo Domingo Yodohino" },
        { code: 529, name: "Santos Reyes Yucuna" },
        { code: 549, name: "Tezoatlán de Segura y Luna" },
        { code: 568, name: "Zapotitlán Palmas" }
    ]],
    ["Ixtlán", [
        { code: 1, name: "Abejones" },
        { code: 35, name: "Guelatao de Juárez" },
        { code: 42, name: "Ixtlán de Juárez" },
        { code: 62, name: "Natividad" },
        { code: 173, name: "San Juan Atepec" },
        { code: 191, name: "San Juan Chicomezúchil" },
        { code: 196, name: "San Juan Evangelista Analco" },
        { code: 214, name: "San Juan Quiotepec" },
        { code: 247, name: "Capulálpam de Méndez" },
        { code: 260, name: "San Miguel Aloápam" },
        { code: 262, name: "San Miguel Amatlán" },
        { code: 267, name: "San Miguel del Río" },
        { code: 288, name: "San Miguel Yotao" },
        { code: 296, name: "San Pablo Macuiltianguis" },
        { code: 335, name: "San Pedro Yaneri" },
        { code: 336, name: "San Pedro Yólox" },
        { code: 359, name: "Santa Ana Yareni" },
        { code: 363, name: "Santa Catarina Ixtepeji" },
        { code: 365, name: "Santa Catarina Lachatao" },
        { code: 419, name: "Santa María Jaltianguis" },
        { code: 443, name: "Santa María Yavesía" },
        { code: 458, name: "Santiago Comaltepec" },
        { code: 473, name: "Santiago Laxopa" },
        { code: 496, name: "Santiago Xiacui" },
        { code: 504, name: "Nuevo Zoquiápam" },
        { code: 544, name: "Teococuilco de Marcos Pérez" }
    ]],
    ["Jamiltepec", [
        { code: 56, name: "Mártires de Tacubaya" },
        { code: 70, name: "Pinotepa de Don Luis" },
        { code: 82, name: "San Agustín Chayuco" },
        { code: 90, name: "San Andrés Huaxpaltepec" },
        { code: 111, name: "San Antonio Tepetlapa" },
        { code: 168, name: "San José Estancia Grande" },
        { code: 180, name: "San Juan Bautista Lo de Soto" },
        { code: 185, name: "San Juan Cacahuatepec" },
        { code: 188, name: "San Juan Colorado" },
        { code: 225, name: "San Lorenzo" },
        { code: 285, name: "San Miguel Tlacamama" },
        { code: 302, name: "San Pedro Atoyac" },
        { code: 312, name: "San Pedro Jicayán" },
        { code: 345, name: "San Sebastián Ixcapa" },
        { code: 367, name: "Santa Catarina Mechoacán" },
        { code: 402, name: "Santa María Cortijo" },
        { code: 414, name: "Santa María Huazolotitlán" },
        { code: 466, name: "Santiago Ixtayutla" },
        { code: 467, name: "Santiago Jamiltepec" },
        { code: 474, name: "Santiago Llano Grande" },
        { code: 482, name: "Santiago Pinotepa Nacional" },
        { code: 485, name: "Santiago Tapextla" },
        { code: 489, name: "Santiago Tetepec" },
        { code: 507, name: "Santo Domingo Armenta" }
    ]],
    ["Juchitán", [
        { code: 5, name: "Asunción Ixtaltepec" },
        { code: 10, name: "El Barrio de la Soledad" },
        { code: 14, name: "Ciudad Ixtepec" },
        { code: 25, name: "Chahuites" },
        { code: 30, name: "El Espinal" },
        { code: 43, name: "Heroica Ciudad de Juchitán de Zaragoza" },
        { code: 57, name: "Matías Romero Avendaño" },
        { code: 66, name: "Santiago Niltepec" },
        { code: 75, name: "Reforma de Pineda" },
        { code: 130, name: "San Dionisio del Mar" },
        { code: 141, name: "San Francisco del Mar" },
        { code: 143, name: "San Francisco Ixhuatán" },
        { code: 198, name: "San Juan Guichicovi" },
        { code: 265, name: "San Miguel Chimalapa" },
        { code: 327, name: "San Pedro Tapanatepec" },
        { code: 407, name: "Santa María Chimalapa" },
        { code: 427, name: "Santa María Petapa" },
        { code: 441, name: "Santa María Xadani" },
        { code: 505, name: "Santo Domingo Ingenio" },
        { code: 513, name: "Santo Domingo Petapa" },
        { code: 525, name: "Santo Domingo Zanatepec" },
        { code: 557, name: "Unión Hidalgo" }
    ]],
    ["Juquila", [
        { code: 153, name: "San Gabriel Mixtepec" },
        { code: 202, name: "San Juan Lachao" },
        { code: 213, name: "San Juan Quiahije" },
        { code: 272, name: "San Miguel Panixtlahuaca" },
        { code: 314, name: "San Pedro Juchatengo" },
        { code: 318, name: "San Pedro Mixtepec - Distrito 22" },
        { code: 334, name: "Villa de Tututepec de Melchor Ocampo" },
        { code: 364, name: "Santa Catarina Juquila" },
        { code: 433, name: "Santa María Temaxcaltepec" },
        { code: 497, name: "Santiago Yaitepec" },
        { code: 526, name: "Santos Reyes Nopala" },
        { code: 543, name: "Tataltepec de Valdés" }
    ]],
    ["Juxtlahuaca", [
        { code: 16, name: "Coicoyán de las Flores" },
        { code: 208, name: "San Juan Mixtepec -Distrito 08-" },
        { code: 242, name: "San Martín Peras" },
        { code: 286, name: "San Miguel Tlacotepec" },
        { code: 348, name: "San Sebastián Tecomaxtlahuaca" },
        { code: 469, name: "Santiago Juxtlahuaca" },
        { code: 528, name: "Santos Reyes Tepejillo" }
    ]],
    ["Miahuatlán", [
        { code: 59, name: "Miahuatlán de Porfirio Díaz" },
        { code: 61, name: "Monjas" },
        { code: 95, name: "San Andrés Paxtlán" },
        { code: 126, name: "San Cristóbal Amatlán" },
        { code: 146, name: "San Francisco Logueche" },
        { code: 148, name: "San Francisco Ozolotepec" },
        { code: 154, name: "San Ildefonso Amatlán" },
        { code: 159, name: "San Jerónimo Coatlán" },
        { code: 167, name: "San José del Peñasco" },
        { code: 170, name: "San José Lachiguiri" },
        { code: 209, name: "San Juan Mixtepec -Distrito 26-" },
        { code: 211, name: "San Juan Ozolotepec" },
        { code: 235, name: "San Luis Amatlán" },
        { code: 236, name: "San Marcial Ozolotepec" },
        { code: 254, name: "San Mateo Río Hondo" },
        { code: 263, name: "San Miguel Coatlán" },
        { code: 279, name: "San Miguel Suchixtepec" },
        { code: 289, name: "San Nicolás" },
        { code: 291, name: "San Pablo Coatlán" },
        { code: 319, name: "San Pedro Mixtepec -Distrito 26-" },
        { code: 344, name: "San Sebastián Coatlán" },
        { code: 347, name: "San Sebastián Río Hondo" },
        { code: 351, name: "San Simón Almolongas" },
        { code: 353, name: "Santa Ana" },
        { code: 362, name: "Santa Catarina Cuixtla" },
        { code: 384, name: "Santa Cruz Xitla" },
        { code: 391, name: "Santa Lucía Miahuatlán" },
        { code: 424, name: "Santa María Ozolotepec" },
        { code: 495, name: "Santiago Xanica" },
        { code: 512, name: "Santo Domingo Ozolotepec" },
        { code: 533, name: "Santo Tomás Tamazulapan" },
        { code: 538, name: "Sitio de Xitlapehua" }
    ]],
    ["Mixe", [
        { code: 3, name: "Asunción Cacalotepec" },
        { code: 31, name: "Tamazulápam del Espíritu Santo" },
        { code: 60, name: "Mixistlán de la Reforma" },
        { code: 190, name: "San Juan Cotzocón" },
        { code: 207, name: "San Juan Mazatlán" },
        { code: 231, name: "San Lucas Camotlán" },
        { code: 275, name: "San Miguel Quetzaltepec" },
        { code: 323, name: "San Pedro Ocotepec" },
        { code: 337, name: "San Pedro y San Pablo Ayutla" },
        { code: 394, name: "Santa María Alotepec" },
        { code: 435, name: "Santa María Tepantlali" },
        { code: 437, name: "Santa María Tlahuitoltepec" },
        { code: 454, name: "Santiago Atitlán" },
        { code: 465, name: "Santiago Ixcuintepec" },
        { code: 502, name: "Santiago Zacatepec" },
        { code: 517, name: "Santo Domingo Tepuxtepec" },
        { code: 554, name: "Totontepec Villa de Morelos" }
    ]],
    ["Nochixtlán", [
        { code: 6, name: "Asunción Nochixtlán" },
        { code: 46, name: "Magdalena Jaltepec" },
        { code: 54, name: "Magdalena Zahuatlán" },
        { code: 94, name: "San Andrés Nuxiño" },
        { code: 96, name: "San Andrés Sinaxtla" },
        { code: 140, name: "San Francisco Chindúa" },
        { code: 144, name: "San Francisco Jaltepetongo" },
        { code: 147, name: "San Francisco Nuxaño" },
        { code: 195, name: "San Juan Diuxi" },
        { code: 215, name: "San Juan Sayultepec" },
        { code: 217, name: "San Juan Tamazola" },
        { code: 224, name: "San Juan Yucuita" },
        { code: 250, name: "San Mateo Etlatongo" },
        { code: 255, name: "San Mateo Sindihui" },
        { code: 264, name: "San Miguel Chicahua" },
        { code: 270, name: "San Miguel Huautla" },
        { code: 274, name: "San Miguel Piedras" },
        { code: 281, name: "San Miguel Tecomatlán" },
        { code: 304, name: "San Pedro Coxcaltepec Cántaros" },
        { code: 329, name: "San Pedro Teozacoalco" },
        { code: 331, name: "San Pedro Tidaá" },
        { code: 395, name: "Santa María Apazco" },
        { code: 404, name: "Santa María Chachoápam" },
        { code: 451, name: "Santiago Apoala" },
        { code: 463, name: "Santiago Huauclilla" },
        { code: 492, name: "Santiago Tilantongo" },
        { code: 493, name: "Santiago Tillo" },
        { code: 511, name: "Santo Domingo Nuxaá" },
        { code: 523, name: "Santo Domingo Yanhuitlán" },
        { code: 562, name: "Magdalena Yodocono de Porfirio Díaz" },
        { code: 564, name: "Yutanduchi de Guerrero" },
        { code: 569, name: "Santa Inés de Zaragoza" }
    ]],
    ["Ocotlán", [
        { code: 7, name: "Asunción Ocotlán" },
        { code: 49, name: "Magdalena Ocotlán" },
        { code: 68, name: "Ocotlán de Morelos" },
        { code: 72, name: "San José del Progreso" },
        { code: 103, name: "San Antonino Castillo Velasco" },
        { code: 112, name: "San Baltazar Chichicápam" },
        { code: 132, name: "San Dionisio Ocotlán" },
        { code: 162, name: "San Jerónimo Taviche" },
        { code: 192, name: "San Juan Chilateca" },
        { code: 243, name: "San Martín Tilcajete" },
        { code: 284, name: "San Miguel Tilquiápam" },
        { code: 301, name: "San Pedro Apóstol" },
        { code: 315, name: "San Pedro Mártir" },
        { code: 328, name: "San Pedro Taviche" },
        { code: 360, name: "Santa Ana Zegache" },
        { code: 368, name: "Santa Catarina Minas" },
        { code: 393, name: "Santa Lucía Ocotlán" },
        { code: 452, name: "Santiago Apóstol" },
        { code: 530, name: "Santo Tomás Jalieza" },
        { code: 561, name: "Yaxe" }
    ]],
    ["Pochutla", [
        { code: 12, name: "Candelaria Loxicha" },
        { code: 71, name: "Pluma Hidalgo" },
        { code: 85, name: "San Agustín Loxicha" },
        { code: 113, name: "San Baltazar Loxicha" },
        { code: 117, name: "San Bartolomé Loxicha" },
        { code: 253, name: "San Mateo Piñas" },
        { code: 266, name: "San Miguel del Puerto" },
        { code: 306, name: "San Pedro el Alto" },
        { code: 324, name: "San Pedro Pochutla" },
        { code: 366, name: "Santa Catarina Loxicha" },
        { code: 401, name: "Santa María Colotepec" },
        { code: 413, name: "Santa María Huatulco" },
        { code: 439, name: "Santa María Tonameca" },
        { code: 509, name: "Santo Domingo de Morelos" }
    ]],
    ["Putla", [
        { code: 20, name: "Constancia del Rosario" },
        { code: 37, name: "Mesones Hidalgo" },
        { code: 73, name: "Putla Villa de Guerrero" },
        { code: 76, name: "La Reforma" },
        { code: 88, name: "San Andrés Cabecera Nueva" },
        { code: 300, name: "San Pedro Amuzgos" },
        { code: 377, name: "Santa Cruz Itundujia" },
        { code: 392, name: "Santa Lucía Monteverde" },
        { code: 415, name: "Santa María Ipalapa" },
        { code: 447, name: "Santa María Zacatepec" }
    ]],
    ["Silacayoapam", [
        { code: 11, name: "Calihualá" },
        { code: 34, name: "Guadalupe de Ramírez" },
        { code: 65, name: "Ixpantepec Nieves" },
        { code: 81, name: "San Agustín Atenango" },
        { code: 99, name: "San Andrés Tepetlapa" },
        { code: 152, name: "San Francisco Tlapancingo" },
        { code: 183, name: "San Juan Bautista Tlachichilco" },
        { code: 186, name: "San Juan Cieneguilla" },
        { code: 199, name: "San Juan Ihualtepec" },
        { code: 230, name: "San Lorenzo Victoria" },
        { code: 251, name: "San Mateo Nejápam" },
        { code: 259, name: "San Miguel Ahuehuetitlán" },
        { code: 290, name: "San Nicolás Hidalgo" },
        { code: 376, name: "Santa Cruz de Bravo" },
        { code: 461, name: "Santiago del Río" },
        { code: 484, name: "Santiago Tamazola" },
        { code: 501, name: "Santiago Yucuyachi" },
        { code: 537, name: "Silacayoápam" },
        { code: 567, name: "Zapotitlán Lagunas" }
    ]],
    ["Sola de vega", [
        { code: 137, name: "San Francisco Cahuacúa" },
        { code: 149, name: "San Francisco Sola" },
        { code: 155, name: "San Ildefonso Sola" },
        { code: 158, name: "San Jacinto Tlacotepec" },
        { code: 229, name: "San Lorenzo Texmelucan" },
        { code: 277, name: "Villa Sola de Vega" },
        { code: 386, name: "Santa Cruz Zenzontepec" },
        { code: 420, name: "Santa María Lachixío" },
        { code: 429, name: "Santa María Sola" },
        { code: 448, name: "Santa María Zaniza" },
        { code: 450, name: "Santiago Amoltepec" },
        { code: 477, name: "Santiago Minas" },
        { code: 491, name: "Santiago Textitlán" },
        { code: 516, name: "Santo Domingo Teojomulco" },
        { code: 535, name: "San Vicente Lachixío" },
        { code: 566, name: "San Mateo Yucutindoo" }
    ]],
    ["Tehuantepec", [
        { code: 36, name: "Guevea de Humboldt" },
        { code: 52, name: "Magdalena Tequisistlán" },
        { code: 53, name: "Magdalena Tlacotepec" },
        { code: 79, name: "Salina Cruz" },
        { code: 124, name: "San Blas Atempa" },
        { code: 248, name: "San Mateo del Mar" },
        { code: 282, name: "San Miguel Tenango" },
        { code: 305, name: "San Pedro Comitancillo" },
        { code: 307, name: "San Pedro Huamelula" },
        { code: 308, name: "San Pedro Huilotepec" },
        { code: 412, name: "Santa María Guienagati" },
        { code: 418, name: "Santa María Jalapa del Marqués" },
        { code: 421, name: "Santa María Mixtequilla" },
        { code: 440, name: "Santa María Totolapilla" },
        { code: 453, name: "Santiago Astata" },
        { code: 470, name: "Santiago Lachiguiri" },
        { code: 472, name: "Santiago Laollaga" },
        { code: 508, name: "Santo Domingo Chihuitán" },
        { code: 515, name: "Santo Domingo Tehuantepec" }
    ]],
    ["Teotitlán", [
        { code: 29, name: "Eloxochitlán de Flores Magón" },
        { code: 40, name: "Huautepec" },
        { code: 41, name: "Huautla de Jiménez" },
        { code: 58, name: "Mazatlán Villa de Flores" },
        { code: 109, name: "San Antonio Nanahuatípam" },
        { code: 116, name: "San Bartolomé Ayautla" },
        { code: 142, name: "San Francisco Huehuetlán" },
        { code: 163, name: "San Jerónimo Tecóatl" },
        { code: 171, name: "San José Tenango" },
        { code: 187, name: "San Juan Coatzóspam" },
        { code: 206, name: "San Juan de los Cués" },
        { code: 228, name: "San Lorenzo Cuaunecuiltitla" },
        { code: 234, name: "San Lucas Zoquiápam" },
        { code: 244, name: "San Martín Toxpalan" },
        { code: 249, name: "San Mateo Yoloxochitlán" },
        { code: 322, name: "San Pedro Ocopetatillo" },
        { code: 354, name: "Santa Ana Ateixtlahuaca" },
        { code: 374, name: "Santa Cruz Acatepec" },
        { code: 396, name: "Santa María la Asunción" },
        { code: 406, name: "Santa María Chilchotla" },
        { code: 416, name: "Santa María Ixcatlán" },
        { code: 431, name: "Santa María Tecomavaca" },
        { code: 434, name: "Santa María Teopoxco" },
        { code: 490, name: "Santiago Texcalcingo" },
        { code: 545, name: "Teotitlán de Flores Magón" }
    ]],
    ["Teposcolula", [
        { code: 93, name: "San Andrés Lagunas" },
        { code: 105, name: "San Antonino Monte Verde" },
        { code: 106, name: "San Antonio Acutla" },
        { code: 121, name: "San Bartolo Soyaltepec" },
        { code: 221, name: "San Juan Teposcolula" },
        { code: 321, name: "San Pedro Nopala" },
        { code: 332, name: "San Pedro Topiltepec" },
        { code: 339, name: "San Pedro y San Pablo Teposcolula" },
        { code: 341, name: "San Pedro Yucunama" },
        { code: 346, name: "San Sebastián Nicananduta" },
        { code: 405, name: "Villa de Chilapa de Díaz" },
        { code: 423, name: "Santa María Nduayaco" },
        { code: 479, name: "Santiago Nejapilla" },
        { code: 486, name: "Villa Tejúpam de la Unión" },
        { code: 499, name: "Santiago Yolomécatl" },
        { code: 518, name: "Santo Domingo Tlatayápam" },
        { code: 521, name: "Santo Domingo Tonaltepec" },
        { code: 536, name: "San Vicente Nuñú" },
        { code: 540, name: "Villa de Tamazulápam del Progreso" },
        { code: 547, name: "Teotongo" },
        { code: 556, name: "La Trinidad Vista Hermosa" }
    ]],
    ["Tlacolula", [
        { code: 51, name: "Magdalena Teitipac" },
        { code: 78, name: "Rojas de Cuauhtémoc" },
        { code: 118, name: "San Bartolomé Quialana" },
        { code: 131, name: "San Dionisio Ocotepec" },
        { code: 145, name: "San Francisco Lachigoló" },
        { code: 194, name: "San Juan del Río" },
        { code: 197, name: "San Juan Guelavia" },
        { code: 219, name: "San Juan Teitipac" },
        { code: 226, name: "San Lorenzo Albarradas" },
        { code: 233, name: "San Lucas Quiaviní" },
        { code: 298, name: "San Pablo Villa de Mitla" },
        { code: 325, name: "San Pedro Quiatoni" },
        { code: 333, name: "San Pedro Totolápam" },
        { code: 343, name: "San Sebastián Abasolo" },
        { code: 349, name: "San Sebastián Teitipac" },
        { code: 356, name: "Santa Ana del Valle" },
        { code: 380, name: "Santa Cruz Papalutla" },
        { code: 411, name: "Santa María Guelacé" },
        { code: 449, name: "Santa María Zoquitlán" },
        { code: 475, name: "Santiago Matatlán" },
        { code: 506, name: "Santo Domingo Albarradas" },
        { code: 546, name: "Teotitlán del Valle" },
        { code: 550, name: "San Jerónimo Tlacochahuaya" },
        { code: 551, name: "Tlacolula de Matamoros" },
        { code: 560, name: "Villa Díaz Ordaz" }
    ]],
    ["Tlaxiaco", [
        { code: 26, name: "Chalcatongo de Hidalgo" },
        { code: 50, name: "Magdalena Peñasco" },
        { code: 86, name: "San Agustín Tlacotepec" },
        { code: 110, name: "San Antonio Sinicahua" },
        { code: 119, name: "San Bartolomé Yucuañe" },
        { code: 127, name: "San Cristóbal Amoltepec" },
        { code: 133, name: "San Esteban Atatlahuca" },
        { code: 172, name: "San Juan Achiutla" },
        { code: 210, name: "San Juan Numi" },
        { code: 218, name: "San Juan Teita" },
        { code: 239, name: "San Martín Huamelulpam" },
        { code: 240, name: "San Martín Itunyoso" },
        { code: 252, name: "San Mateo Peñasco" },
        { code: 258, name: "San Miguel Achiutla" },
        { code: 269, name: "San Miguel el Grande" },
        { code: 297, name: "San Pablo Tijaltepec" },
        { code: 317, name: "San Pedro Mártir Yucuxaco" },
        { code: 320, name: "San Pedro Molinos" },
        { code: 370, name: "Santa Catarina Tayata" },
        { code: 371, name: "Santa Catarina Ticuá" },
        { code: 372, name: "Santa Catarina Yosonotú" },
        { code: 379, name: "Santa Cruz Nundaco" },
        { code: 382, name: "Santa Cruz Tacahua" },
        { code: 383, name: "Santa Cruz Tayata" },
        { code: 397, name: "Heroica Ciudad de Tlaxiaco" },
        { code: 408, name: "Santa María del Rosario" },
        { code: 430, name: "Santa María Tataltepec" },
        { code: 444, name: "Santa María Yolotepec" },
        { code: 445, name: "Santa María Yosoyúa" },
        { code: 446, name: "Santa María Yucuhiti" },
        { code: 480, name: "Santiago Nundiche" },
        { code: 481, name: "Santiago Nuyoó" },
        { code: 500, name: "Santiago Yosondúa" },
        { code: 510, name: "Santo Domingo Ixcatlán" },
        { code: 532, name: "Santo Tomás Ocotepec" }
    ]],
    ["Tuxtepec", [
        { code: 2, name: "Acatlán de Pérez Figueroa" },
        { code: 9, name: "Ayotzintepec" },
        { code: 21, name: "Cosolapa" },
        { code: 44, name: "Loma Bonita" },
        { code: 134, name: "San Felipe Jalapa de Díaz" },
        { code: 136, name: "San Felipe Usila" },
        { code: 166, name: "San José Chiltepec" },
        { code: 169, name: "San José Independencia" },
        { code: 184, name: "San Juan Bautista Tuxtepec" },
        { code: 232, name: "San Lucas Ojitlán" },
        { code: 278, name: "San Miguel Soyaltepec" },
        { code: 309, name: "San Pedro Ixcatlán" },
        { code: 417, name: "Santa María Jacatepec" },
        { code: 559, name: "San Juan Bautista Valle Nacional" }
    ]],
    ["Villa Alta", [
        { code: 38, name: "Villa Hidalgo Yalálag" },
        { code: 97, name: "San Andrés Solaga" },
        { code: 100, name: "San Andrés Yaá" },
        { code: 114, name: "San Baltazar Yatzachi el Bajo" },
        { code: 120, name: "San Bartolomé Zoogocho" },
        { code: 128, name: "San Cristóbal Lachirioag" },
        { code: 138, name: "San Francisco Cajonos" },
        { code: 156, name: "San Ildefonso Villa Alta" },
        { code: 201, name: "San Juan Juquila Vijanos" },
        { code: 216, name: "San Juan Tabaá" },
        { code: 222, name: "San Juan Yaeé" },
        { code: 223, name: "San Juan Yatzona" },
        { code: 246, name: "San Mateo Cajonos" },
        { code: 257, name: "San Melchor Betaza" },
        { code: 280, name: "Villa Talea de Castro" },
        { code: 299, name: "San Pablo Yaganiza" },
        { code: 303, name: "San Pedro Cajonos" },
        { code: 432, name: "Santa María Temaxcalapa" },
        { code: 442, name: "Santa María Yalina" },
        { code: 457, name: "Santiago Camotlán" },
        { code: 471, name: "Santiago Lalopa" },
        { code: 503, name: "Santiago Zoochila" },
        { code: 514, name: "Santo Domingo Roayaga" },
        { code: 522, name: "Santo Domingo Xagacía" },
        { code: 541, name: "Tanetze de Zaragoza" }
    ]],
    ["Yautepec", [
        { code: 8, name: "Asunción Tlacolulita" },
        { code: 64, name: "Nejapa de Madero" },
        { code: 74, name: "Santa Catarina Quioquitani" },
        { code: 122, name: "San Bartolo Yautepec" },
        { code: 125, name: "San Carlos Yautepec" },
        { code: 200, name: "San Juan Juquila Mixes" },
        { code: 204, name: "San Juan Lajarcia" },
        { code: 316, name: "San Pedro Mártir Quiechapa" },
        { code: 357, name: "Santa Ana Tavela" },
        { code: 361, name: "Santa Catalina Quierí" },
        { code: 410, name: "Santa María Ecatepec" },
        { code: 428, name: "Santa María Quiegolani" }
    ]],
    ["Zaachila", [
        { code: 108, name: "San Antonio Huitepec" },
        { code: 273, name: "San Miguel Peras" },
        { code: 292, name: "San Pablo Cuatro Venados" },
        { code: 388, name: "Santa Inés del Monte" },
        { code: 555, name: "Trinidad Zaáchila" },
        { code: 565, name: "Villa de Zaáchila" }
    ]],
    ["Zimatlán", [
        { code: 13, name: "Ciénega de Zimatlán" },
        { code: 48, name: "Magdalena Mixtepec" },
        { code: 104, name: "San Antonino el Alto" },
        { code: 123, name: "San Bernardo Mixtepec" },
        { code: 271, name: "San Miguel Mixtepec" },
        { code: 295, name: "San Pablo Huixtepec" },
        { code: 358, name: "Santa Ana Tlapacoyan" },
        { code: 369, name: "Santa Catarina Quiané" },
        { code: 378, name: "Santa Cruz Mixtepec" },
        { code: 387, name: "Santa Gertrudis" },
        { code: 389, name: "Santa Inés Yatzeche" },
        { code: 398, name: "Ayoquezco de Aldama" },
        { code: 570, name: "Zimatlán de Álvarez" }
    ]]
]);